name: PY test

on: 
  workflow_dispatch:
  repository_dispatch:
    types: [my-event]
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Appium-Python-Client
        pip install pytest
    - name: Test with pytest
      run: |
        pytest
#     - name: Saucelabs delete and upload
#       env:
#         SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
#         SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
#       run: |
#         curl -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location \
#         --request DELETE 'https://api.us-west-1.saucelabs.com/v1/storage/groups/1696366' | json_pp
